name: Build and Push Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  DOTNET_VERSION: '6.0.x' 
  CONTAINER_REGISTRY: 'acrxhagua.azurecr.io'
  CONTAINER_REPOSITORY: 'xhagua-aks-backend'
  PUBLISH_FOLDER: 'publish'

defaults:
  run:
    working-directory: ./src
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    

 
